### PR TITLE
Add some invalid test vectors

### PR DESCRIPTION
**Pull request by roconnor-blockstream**

### CODE REVIEW

**Comment by apoelstra** [comment]
These are great, thank you!

**Comment by apoelstra** [comment]
Accepted by cherry-pick. I did not carefully vet these ones. But I'll start working on a rust reference implementation and check them then.

**Comment by apoelstra** [comment]
Should add one with mixed case in the HRP but consistent case everywhere else.

**Comment by roconnor-blockstream** [comment]
Resurrected PR.

**Comment by apoelstra** [comment]
Thanks! Accepted by cherry-pick.

The BIP is almost good to go -- I just want to merge https://github.com/BlockstreamResearch/codex32/pull/50 and add a link to the resulting repo.

**Pull request closed without merging**
